title: iiMEli 2020
email: iimeli2020@gmail.com
description: Eli Smith (@iimeli), personal website &amp; portfolio. Software developer, open source enthusiast.

exclude: [
  'LICENSE.md',
  'README.md'
]